region = "us-west-2" //oregon region
project = "poc"
env = "dev"
vpc_cidr = "10.219.0.0/18"   //dummy cidr
public_subnet_cidr = "10.219.50.0/23" //dummy subnet
private_subnet_cidr = "10.219.0.0/20" //dummy subnet
route_ass_count = "1"
public_subnet_count = "1"
private_subnet_count = "1"
ec2_allowed_cidr_block = "10.219.0.0/32" //dummy IP
application_port = "8080" //dummy application port
db_port = "5432" //postgres
alb_cidr_blocks = "10.219.0.0/32" //dummy ip
ami = "ami-xxxxxxxxxxx" //dummy ami ID
instance_type = "t2.medium"
engine                          = "aurora-postgresql" //postgres
engine_version                  = "12.8"  //version
auto_minor_version_upgrade      = true
family                          = "aurora-postgresql12"
master_username                 = "admin"
master_password                 = "agvayfahbakna" 
backup_retention_period         = "30"
preferred_backup_window         = "02:00-03:00"
preferred_maintenance_window    = "wed:03:00-wed:04:00"
skip_final_snapshot             = true
enabled_cloudwatch_logs_exports = ["postgresql"]
rds_instance_count              = "1"
kms_key_id                      = "arn:aws:kms:us-west-2:XXXXXXX:key/XXXXXXXXXXXXXXXXXXXXX"
engine_mode                     = "provisioned"
enable_http_endpoint            = false
identifier                      = "postgres"
database_name                   = "postgres"
instance_class                  = "db.t3.medium"
alb_cert_arn         = "arn:aws:acm:us-west-2:XXXXXXXXXXXX:certificate/XXXXXXXXXXXXXXXXXXX"
deregistration_delay = "300"
health_check_path    = "/"
